
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wra-based-on-reanalysis-data"
version = "1.0.0"
author = [
  { name="Emilio Barrachina GascÃ³", email="emilio.barrachinagasco@iicv.es" },
]
description = "Project developing a Python package for WRA at a specified Horn 1 site using ERA5 reanalysis data."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "xarray",
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "seaborn",
    "windrose",
    "netcdf4"
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "mypy", "flake8"]
dev = ["black", "isort", "pre-commit"]

[project.urls]
"Homepage" = "https://github.com/EmilioBG76/Project03_46W38/"

# The source code for the package and its submodules are located in the 'src' directory.
# 'src/main.py' and 'src/functions_module.py'

[tool.setuptools.packages.find]
where = ["src"]


[tool.black]
line-length = 100
target-version = ["py311"]



